services:
  fastapi-app:
    build:
      context: .
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - .:/app
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: requirements.txt
    command:
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload